### PR TITLE
exercise_1.12.2

### PR DESCRIPTION
**Pull request by Ifeanyijasper**
Evaluating different expression that done on python interpreter.

### CODE REVIEW

**Comment by ch3nkula** [comment]
Do a "git pull" from my remote master before making this PR. Some changes have been done on your repo by me to fix the issues!

**Comment by ch3nkula** [comment]
Did you pull from my master branch? What did you get?

**Comment by ch3nkula** [comment]
Issue not still fixed!

**Comment by Ifeanyijasper** [comment]
They told me everything is already up-to-date.

**Pull request closed without merging**
